# Generated by Django 4.1.3 on 2022-11-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_amenities_alter_room_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
