# Generated by Django 4.1.3 on 2022-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rename_created_amenity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
