# Generated by Django 4.1.3 on 2022-11-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_alter_experience_category_alter_experience_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='perk',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='perk',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
