# Generated by Django 4.1.3 on 2022-11-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_photo_file_alter_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
