# Generated by Django 4.1.2 on 2022-11-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_rename_created_photo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
