# Generated by Django 4.1.2 on 2022-11-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_experience_event_duration'),
        ('medias', '0004_photo_is_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='experiences.experience'),
        ),
    ]
