# Generated by Django 4.1.3 on 2022-11-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
