# Generated by Django 4.1.3 on 2022-11-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_experience_alter_review_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
