# Generated by Django 4.1.2 on 2022-11-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_host_approval_state_booking_is_cancelled'),
        ('reviews', '0004_rename_created_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.booking'),
        ),
    ]
