# Generated by Django 4.1.3 on 2022-11-07 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0005_rename_created_experience_created_at_and_more'),
        ('rooms', '0005_rename_created_amenity_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('experiences', models.ManyToManyField(blank=True, related_name='wishlists', to='experiences.experience')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(blank=True, related_name='wishlists', to='rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
